# run para dev.:
#                 docker-compose up angular-dev
# run para prod:
#                 docker-compose up angular-prod --build -d
services:
  # angular-dev:
  #   container_name: main-dev
  #   build:
  #     context: .
  #     dockerfile: Dockerfile.dev
  #   ports:
  #     - "4200:4200"
  #   restart: always

  angular-prod:
    container_name: main-prod
    build:
      context: .
      dockerfile: Dockerfile.prod
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./certbot-var:/var/lib/letsencrypt
      - ./certbot-etc:/etc/letsencrypt
      - ./certbot-www:/var/www/certbot
    environment:
      - VIRTUAL_HOST=msdaniel.com.br
    restart: always

volumes:
  certbot-var:
  certbot-etc:
  certbot-www:
