# run para dev.:
#                 docker-compose up angular-dev
# run para prod:
#                 docker-compose up angular-prod
services:
  angular-dev:
    container_name: main-dev
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "4200:4200"
    restart: always

  angular-prod:
    container_name: main-prod
    build:
      context: .
      dockerfile: Dockerfile.prod
    ports:
      - "80:80"
      - "443:443"
    environment:
      - VIRTUAL_HOST=msdaniel.com.br
    restart: always

  certbot:
    container_name: certbot
    image: certbot/certbot
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
      - ./renewal-hook.sh:/renewal-hook.sh
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew --post-hook \"/renewal-hook.sh\"; sleep 12h & wait $${!}; done;'"
    restart: always

  # a primeira vez que rodar o container e necessario gerar o certificado ao menos uma vez
  # esse comando precisar ser executado antes do container do angular prod
  # docker-compose run --rm certbot certonly --webroot --webroot-path=/var/www/certbot -d msdaniel.com.br

